name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Загрузить репозиторий на локальную ubuntu
      - name: Run Checkout
        uses: actions/checkout@master
        
        # Заполнить env файл через jinja
      - name: Create venv file
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: ./.github/workflows/sample.env.j2
          output_file: ./.github/workflows/sample.env
        #env:
          #URL: ${{ secrets['URL'] }}
          #API_KEY: ${{ secrets['API_KEY'] }}
          
        # Передать его на сервер
      - name: Send file on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATEKEY }}
          source: "./.github/workflows/sample.env"
          target: "~/stock-news"
          
        # Запустить скрипт на сервере, который стянет репозиторий, поставить venv и обновить зависимости 
      - name: Run SSH command
        uses: appleboy/ssh-action@master
        with:
          script: bash server.sh
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATEKEY }}
