name: CI

on:
  push:
    branches: [ main ]

jobs:
  create_envs:
    needs: [build_docker_backend, build_docker_mle]
    runs-on: ubuntu-latest

    steps:
        # Заполнить env файл через jinja
      - name: Create venv file
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: ./.github/workflows/sample.env.j2
          output_file: ./.github/workflows/sample.env
        env:
          URL: ${{ secrets.get('URL') }}
          API_KEY: ${{ secrets.get('API_KEY') }}
          
        # Передаем файлы на сервер
      - name: Send file on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATEKEY }}
          source: "./.github/workflows"
          target: "~/stock-news"
