version: '3'

services:
  service_backend:
    container_name: backend
    image: stocknews/stock-news:backend
    command: "python3 /app/backend/server.py"
    env_file:
      - sample.env
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.0.0.1

  worker_mle:
    container_name: mle
    image: stocknews/stock-news:mle
    command: "python3 /app/data_preprocess/upload_data2mongo.py"
    env_file:
      - sample.env
    dns:
      - 8.8.8.8
      - 1.0.0.1

