version: '3'

services:
  backend:
    container_name: _backend__
    image: stocknews/stock-news:_backend__
    command: python /app/backend/server.py
    env_file:
      - sample.env
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.0.0.1

  mle:
    container_name: _mle__
    image: stocknews/stock-news:_mle__
    command: python /app/data_preprocess/upload_data2mongo.py
    env_file:
      - sample.env
    ports:
      - "8081:8081"
    dns:
      - 8.8.8.8
      - 1.0.0.1

