version: '3'

services:
  backend:
    container_name: backend
    image: https://hub.docker.com/repository/docker/stocknews/stock-news:backend
    command: python /app/backend/server.py
    env_file:
      - sample.env
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.0.0.1

  mle:
    container_name: mle
    image: https://hub.docker.com/repository/docker/stocknews/stock-news:mle
    command: python /app/data_preprocess/upload_data2mongo.py
    env_file:
      - sample.env
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.0.0.1

