version: '3'

services:
  backend_:
    container_name: backend__1
    image: stocknews/stock-news:backend__1
    command: python /app/backend/server.py
    env_file:
      - sample.env
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.0.0.1

  mle_:
    container_name: mle__1
    image: stocknews/stock-news:mle__1
    command: python /app/data_preprocess/upload_data2mongo.py
    env_file:
      - sample.env
    ports:
      - "8081:8081"
    dns:
      - 8.8.8.8
      - 1.0.0.1

